### ISSUE TITLE
how to set target="_blank" on search result links

### ISSUE THREAD

**Issue by ruemic** [algolia/docsearch#104]
I'd like to make the links in the widget open in a new tab.

 Is there a blessed path to modify the markup of the search results template so I can add `target="_blank"` to the links returned by a search?

**Comment by pixelastic** [comment]
Hello,

It is not currently possible to change the template of the suggestions to add your own (there is a lot of logic in the templating to handle the multiple categories). That being said, DocSearch is a wrapper on top of `[autocomplete.js](https://github.com/algolia/autocomplete.js)` and you can access every feature of it through the `.autocomplete` key.

DocSearch itself listens to the `on('autocomplete:selected')` event to change the current page url. You can remove our listener and add your own to open the result in a new page instead of the same using something similar to this:

```javascript
var search = docsearch({
  apiKey: 'your_api_key',
  indexName: 'your_index_name',
  inputSelector: '#your_selector'
});

// Removing our listener
search.autocomplete.off('autocomplete:selected');
// Adding yours
search.autocomplete.on('autocomplete:selected', function(event, data) {
  window.open(data.url, '_blank');
});
```

**Comment by ruemic** [comment]
cool thanks!

**Comment by remcokalf** [comment]
For anybody looking how to do this with DocSearch JS in v.3:

You need to use [hitComponent](https://docsearch.algolia.com/docs/api/#hitcomponent) to customize the `<a>` tag of the results. And to create that tag, it needs Preact loaded, which is used by [Algolia Autcomplete JS](https://github.com/algolia/autocomplete), used by DocSearch JS.

The following code will load the results in a new window when clicked. 

However, when using the keyboard arrow keys and enter, DocSearch intercepts this and [navigator](https://docsearch.algolia.com/docs/api/#navigator) will use `navigate` which opens the results in the same tab. If you use CTRL-Enter or CMD-Enter, it uses `navigateNewTab` ( [see the code in DocSearch Autocomplete JS](https://github.com/algolia/autocomplete/blob/47e84f67fd8b66bfdfd00e3be8e8272198ebd066/packages/autocomplete-core/src/getDefaultProps.ts#L93-L103) ) which opens the results in a new tab. To customize the default `navigator` action (using only the Enter key) the code below customizes the `navigator` action to open results in a new window when using Enter. The only downside is that this leads to a popup block message in the brower, but that also happens when using CTRL-Enter in the default situation. I have not found a way to prevent the popup block, this seems inherent to using `window.open()`.

```html
<script src="https://cdn.jsdelivr.net/npm/@docsearch/js@3"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3" />

<script src="https://unpkg.com/preact@latest/dist/preact.umd.js"></script>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const { h } = preact; // load preact.h function
        docsearch({
            container: '#docsearch',
            appId: 'your_appID',
            apiKey: 'your_apiKey',
            indexName: 'your_indexName',
            searchParameters: {
                hitsPerPage: 30
            },
            // Makes clicked result links open in a new window
            // Needs preact loaded
            hitComponent({ hit, children }) {
                // Use preact.h('tag', {props}, children) to create the element
                return preact.h(
                    'a',
                    {
                        href: hit.url,
                        target: '_blank',
                        rel: 'noopener noreferrer'
                    },
                    children
                );
            },
            // Optional, makes results that are keyboard selected with Enter, open in a new window
            // Note: triggers popup blocker of the browser. But that also happens with the default of CTRL-Enter/CMD-Enter
            navigator: {
                navigate({ itemUrl }) {
                    const windowReference = window.open(itemUrl, '_blank', 'noopener noreferrer');
                    windowReference?.focus();
                },
            }
        });
    });

</script>
```
