### ISSUE TITLE
Questions about the service

### ISSUE THREAD

**Issue by blee1170** [algolia/docsearch#120]
I am hoping someone here can help answer some questions for me. I really like docsearch and would like to include it in our documentation, but I cant seem to find anything covering the following questions:

1. Can it securely connect to a different git enterprise? My company has our own github enterprise and thats where our documentation will be stored. 

2. Would our data encrypted on the backend? Security is a major thing for us, and a lot of our documentation would be internal facing.

3. If 1 & 2 cant be done, is there a on prem solution?

Thanks for taking the time to help me out.

**Comment by redox** [comment]
Thank you for your interest in DocSearch @blee1170; GitHub is definitely a good place to chat about that.

> Can it securely connect to a different git enterprise? My company has our own github enterprise and thats where our documentation will be stored.

We actually don't need access to any GitHub repository. We'll configure a crawler that will crawl your website, send the crawled content to an Algolia index and provide you a short JavaScript code snippet to add to all the pages you want to use DocSearch to power the as-you-type search bar.

> Would our data encrypted on the backend? Security is a major thing for us, and a lot of our documentation would be internal facing.

You can read more about our security & infra from here: https://www.algolia.com/infra For DocSearch, the underlying Algolia account that is used to index the crawled pages is hosted on mutualized/multi-tenant machines but we do offer enterprise/single-tenant clusters in case this won't be an option for you. Unfortunately, that won't be the same free/community plan. If you want to know more about that, we would be happy to discuss your specific use-case emailing enterprise@algolia.com

> If 1 & 2 cant be done, is there a on prem solution?

We're about to open-source the underlying DocSearch python crawler; from there you'll be able to run it on your end. This might be required for your use-case because from what I understand you want to index internal documentation (our current setup can only index content that is available on the internet - so we can access it).

You'll still need to send that content to an Algolia account/index to use DocSearch, but again that's definitely something we can provide you in a very secure way.

Let us know!

**Comment by blee1170** [comment]
Thanks for taking the time to reply. 

Do you have any time frame with DocSearch will be out? 

I am looking to incorporate it into [http://couscous.io/](http://couscous.io/) type of document site. Much like these guys did: [http://php-di.org/doc/](http://php-di.org/doc/). Thats why I was asking about github.

The infra page is a little light on describing how the data is encrypted:

```Everything is considered as unsecure, even communications within the same rack are encrypted.``` 

That is not very descriptive on what is being done. Can you elaborate on it any more?

Thanks again for your feed back.

**Comment by redox** [comment]
> Do you have any time frame with DocSearch will be out?

I don't; but I expect it to be open-sourced in the next few weeks.

> The infra page is a little light on describing how the data is encrypted

Sure thing. On the specific encryption topic:
 * the data are stored on disk in a custom data structure (unreadable as-is) but cannot really be encrypted because of the typo-tolerance constraints (same deal for every full-text search engines)
 * nevertheless we do offer encryption at rest for our enterprise customers (whole data partition encrypted)

> I am looking to incorporate it into http://couscous.io/ type of document site.

I think for such use-case we should rather speak about a custom integration of Algolia instead of using DocSearch. Our engineers will be happy to share with you all the hints you need to implement your own docsearch in Couscous.io -> since you've the data in your backend (somehow), it's probably easier than building a crawler.

Maybe you should starting opening a new free account on Algolia.com, play with the API, see how it goes.

You can also read https://blog.algolia.com/how-to-build-a-helpful-search-for-technical-documentation-the-laravel-example/

**Comment by nagim** [comment]
Hi,

I have another question: does the search work offline? We must provide our docs in an offline package as well.

Thanks,
Imre

**Comment by ElPicador** [comment]
Hi @nagim,

No there is no offline mode. DocSearch is using Algolia which is a SaaS product.

**Comment by ElPicador** [comment]
I'm closing this issue. If you need more info don't hesitate to contact support@algolia.com
