### ISSUE TITLE
Migration to new scarper - All pages ignored

### ISSUE THREAD

**Issue by ArthurFlageul** [algolia/docsearch#1222]
## Description

Hello, 

I'm trying the new crawler as per an email I received last week. The new crawler ignores 78 pages and reports success for 2 pages (the home and the sitemap) (these are all my pages). 

The reason for the ignore is always:

> This page attempted to redirect to "http://docs.whateverpage.../", which was refused for this reason: "url_will_not_match_config"

So essentially, it seems the new crawler sees a redirect from HTTPS to HTTP that the former crawler didn't care about (nothing has changed on my end). 

## Expected behavior

[My config](https://github.com/algolia/docsearch-configs/blob/master/configs/talon.json) worked with the previous crawler, so it should work with this crawler the same way.

Or, if I need to edit my config to migrate, where can I find the instructions? The new crawler email announcement said there's nothing to update, but maybe in some cases, there is?

**Comment by shortcuts** [comment]
Hey,

> So essentially, it seems the new crawler sees a redirect from HTTPS to HTTP that the former crawler didn't care about (nothing has changed on my end).

Our new crawler follow settings that are defined on your end. This was an issue with the `docsearch-scraper`, since it causes users to duplicate settings/restrictions in both the website and the config.

> The new crawler email announcement said there's nothing to update, but maybe in some cases, there is?

We tried our best to have the smallest footprint on the migration, but there is indeed some cases where we can't override restrictions and requires you to do some updates!

I'd suggest you to check the configuration of your hosting and maybe redirects on Docusaurus?

#### Documentations:
- (Not for this case) We have documentations regarding the DocSearch extracting here: https://docsearch.algolia.com/docs/migrating-from-legacy/
- General Crawler documentation here: https://www.algolia.com/doc/tools/crawler/getting-started/overview/
- From the Crawler editor, you have access to the `URL tester` which also helps you inspect pages without starting a full crawl

**Comment by bodinsamuel** [comment]
Hello, 
to answer directly your main point.

Your website has trailing slash redirection activated but it points to `http` (no s) instead of `https` and since those are different protocol the `pathsToMatch` are not matching.

```sh
curl -XGET -I https://docs.talon.one/search

HTTP/2 301
content-type: text/html
date: Wed, 15 Dec 2021 13:50:32 GMT
location: http://docs.talon.one/search/
server: nginx/1.19.6
vary: Accept-Encoding
content-length: 169
```

After this initial redirection you get a second one to go back to `https` 
```sh
curl -XGET -I http://docs.talon.one/search/

HTTP/1.1 302 Found
Location: https://docs.talon.one:443/search/
Date: Wed, 15 Dec 2021 13:52:08 GMT
Content-Length: 5
Content-Type: text/plain; charset=utf-8
```

You need to configure your server/CMS to redirect to https and the crawler will work happily crawl your website ☺️ 
Best Regards

**Comment by ArthurFlageul** [comment]
Ah, thank you guys for the quick answers and solution, I didn't realize this 🤦  !
