### ISSUE TITLE
Image missing in the doc

### ISSUE THREAD

**Issue by LukyVj** [algolia/docsearch#125]
![](http://puu.sh/q1Abo/015194800e.png)

**Comment by vvo** [comment]
Quick note @s-pace if you ever fix those issues with commits you can reference them from a commit like fixes #125 in the commit message. https://help.github.com/articles/closing-issues-using-keywords/

Otherwise provide a small comment saying it was fixed. When we close issues without comment then it can be 1. We did not fix it 2. We fixed it. But there's no way to know.

Thanks!
