### ISSUE TITLE
Crawler not running every 24 hours

### ISSUE THREAD

**Issue by kylebebak** [algolia/docsearch#191]
My site http://requester.org is indexed by doc search. It was first indexed 4 days ago.

I removed a section from the site a few days ago, and added another section 2 days ago. Results from the removed section are still showing up, and results from the new section aren't. It would seem the crawler hasn't run in the last 3 days. If it has, the results haven't been added to the index.

I saw in https://github.com/algolia/docsearch/issues/98 that changes to the docs should be visible within 24 hours.

**Comment by s-pace** [comment]
Hi,

We have detected this issue and thus we raised an error. In order to avoid any waste of data, we froze the update of your index. We tried to fix it but your web site was mainly down those days so we stopped looking at it.

Don't worry, we will have a look and everything will be fixed up within the 24h.

Best,

**Comment by kylebebak** [comment]
Thank you for the update!

**Comment by s-pace** [comment]
​The issue came from the fact that you change the ID of the DOM object containing the data to index (#content).
​
​I have updated, tested and deployed it. Please have a look to the simple [modification here](https://github.com/algolia/docsearch-configs/commit/534e64f20af1f31a16f7cf5fd30ec541dfd9443d).​
​
​Everything is fine, live and working well,
​
​Let us know if you need further information,
