### ISSUE TITLE
Crawler: "No records extracted"

### ISSUE THREAD

**Issue by artembelik** [algolia/docsearch#2272]
Hi, crawler doesn't find records, it seems that the "renderJavaScript" option fails

```
appId: '7N2W9AKEM6',
indexName: 'koobiq',
```
![image](https://github.com/algolia/docsearch/assets/24925224/c60adc8a-f9df-48f4-9325-050c0676169f)
![image](https://github.com/algolia/docsearch/assets/24925224/2a5c512f-e63f-48b1-a617-0cb566c4edaa)

**Comment by randombeeper** [comment]
Understood. I think I've confirmed this. Asking for feedback internally.

**Comment by randombeeper** [comment]
Discussed in public within our Discord server at https://discord.com/channels/1171089640443367494/1260606320726507550. tldr; we think that the crawler is being blocked due to the region. Best suggestion is to run your own crawler, you can start with our scraper if you prefer: https://github.com/algolia/docsearch-scraper
