### ISSUE TITLE
View usage data?

### ISSUE THREAD

**Issue by m-allanson** [algolia/docsearch#346]
Firstly thanks for DocSearch, it's being used very successfully over on gatsbyjs.org 🎉 

**Do you want to request a *feature* or report a *bug*?**

A feature - is there any way to see usage analytics for a site that's implemented DocSearch? There's one old issue (https://github.com/algolia/docsearch/issues/99) that suggests it's possible, but I can't find any other info about it.

Refs: https://github.com/gatsbyjs/gatsby/issues/5509

**What is the current behavior?**

Unknown whether it's possible to view analytics on DocSearch usage.

**What is the expected behavior?**

Ability to view usage data for a site that has implemented DocSearch.

**Comment by s-pace** [comment]
👋 @m-allanson 

Thank you for the feedback.


We do provide the algolia analytics for free on your DocSearch index.

In order to provide you the right analytics, please send us the email addresses of the people to grant access. (You can use the previous email thread or docsearch at algolia.com)

Cheers

**Comment by m-allanson** [comment]
That's great, thanks!

**Comment by shannonbux** [comment]
@s-pace Thank you! I just sent an email to docsearch@algolia.com

**Comment by s-pace** [comment]
👋 @shannonbux , Invitations done
