### ISSUE TITLE
A question about i18n configuration

### ISSUE THREAD

**Issue by Justineo** [algolia/docsearch#599]
**Is your issue related to your own DocSearch implementation?**

It's a general usage question. I saw in the [docs](https://community.algolia.com/docsearch/config-file.html#using-regular-expressions) that we can configure certain part in URL to match language/version facets. But what if I have a default language like this:

```
http://www.example.com/docs/installation    -> en
http://www.example.com/docs/fr/installation -> fr
http://www.example.com/docs/jp/installation -> jp
```

And the following config should help docsearch to recognize language facets like `fr` and `jp`:

```json
{
  "start_urls": [
    {
      "url": "http://www.example.com/docs/(?:(?P<lang>.*?)/)?",
      "variables": {
        "lang": ["fr", "jp"]
      }
    }
  ]
}
```

My question is, in this case, how can I configure for the default language (`en`) so that on English pages docsearch only return those results not matching any language facets? Thanks in advance.

**Comment by s-pace** [comment]
👋 @Justineo 

You should rely on the content of your pages instead of relying on the URL. You can either:
- [introduces DocSearch meta tags](https://community.algolia.com/docsearch/recommended-configuration.html#introduces-global-information-as-meta-tags) within your DOM
- extract the `lang` attributes from your DOM (as defined by the update of your configuration below).

You will need to update your JS snippet as following:

```js
docsearch({
  apiKey: '21cdc123c620ec4bb81259c32e90c08f',
  indexName: 'veui',
  inputSelector: '### REPLACE ME ####',
  algoliaOptions: { 'facetFilters': ["lang:$LANG"] },
  debug: false // Set debug to true if you want to inspect the dropdown
});
```
- Replace `$LANG` with the lang you want to search on. The list of possible lang is extracted from your website according to [your global `lang` selector](https://github.com/algolia/docsearch-configs/commit/ac9405f7b27385a8cd56d62a89fe68c6e9698cf7). So as of today you have: `en-US`, `zh-Hans`

  For example if you want to refine the search to the lang `en-US` just specify:
```js
 'facetFilters': ["lang:en-US"]
```

**Comment by Justineo** [comment]
@s-pace

Thanks! I have a further question: how can I properly re-initialize the docsearch after it's initialized? My site is using a front-end router so that I need to switch language at runtime.

**Comment by s-pace** [comment]
Your index will be updated every 24H. You will need to wait for the next crawl to be able to update your front. You can [run our crawler on your own](https://community.algolia.com/docsearch/run-your-own.html) if you want more control. You will need you own algolia account

**Comment by Justineo** [comment]
@s-pace 

I mean the `docsearch.js` API in the browser. I cannot find an API to change `facetFilters` setting or just dispose the old instance so that I can initialize again.
