### ISSUE TITLE
JS and website release process

### ISSUE THREAD

**Issue by vvo** [algolia/docsearch#7]
Be able to npm run release much like instantsearch.js

**Comment by pixelastic** [comment]
I just did a release (0.0.7), this went smoothly, except for one hiccup.

@Jerskouille recently added the `build:docs` npm task that will create a `documentation.md` file in the `./docs` Jekyll folder from the `README.md` (using custom seperators). `build:docs` is run from `build`, so at the end of the release I ended up with an unclean git index (`documentation.md` has been updated).

I guess this is due to the fact that

- The release process runs `npm run build`
- `npm run build:docs` wasn't properly fired on develop/feature branches before

No big deal, but I'm unsure as to where this new task should fit in the worflow. We will want to update the doc/website without triggering a whole new release.

**Comment by Jerskouille** [comment]
In `algoliasearch-zendesk`, I actually have a specific script for releasing docs:
```sh
version=`cat package.json | json version`

npm run docs
git add docs
git commit docs -m "docs(release): v$version"
git push

# Then the release part (jekyll build, push to gh-pages, etc.)
```

**Comment by vvo** [comment]
Pushing to master should update the website if something changed ind docs/ (to force update in instantsearch.js I added a "updated $date" in footer)

**Comment by vvo** [comment]
Indeed If we have an automatic jsdoc thing then its harder to automate without a release it could be done via algobot and a commit from travis though.

Otherwise locally running the build docs task then pushing to master should update the website
