### ISSUE TITLE
OpenSearch support

### ISSUE THREAD

**Issue by oliviertassinari** [algolia/docsearch#769]
Hi, we have been exploring OpenSearch support for Material-UI in https://github.com/mui-org/material-ui/pull/16764 (by @merceyz). The implementation has proven to be challenging for us to implement.

Algolia has a short guide about it: https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/opensearch/js/. I'm wondering if it would make sense to solve the problem at the docsearch level?

**Comment by Haroenv** [comment]
What docsearch is missing for this is url synchronisation, which is possible, but not very straightforward. If that would be added, would it be enabled on mui?

**Comment by oliviertassinari** [comment]
@Haroenv To be honest, I don't know if developers will use this browser feature. MUI would be interested to try it out. The end results I had in mind, was a search results page hosted by Algolia, with links that point to the right documentation URL. Do you have the stats usage of the feature on Yarn side? I could help decide if its worth doing.

**Comment by Haroenv** [comment]
For yarn it’s somewhat different because it’s not returning documentation results, just the packages. I don’t have any usage numbers though. 

You can try it out by adding a simple page which show the results based on the query instead of a dropdown. 

Sorry for closing, it was an accident.

**Comment by oliviertassinari** [comment]
@Haroenv Thanks for the update, I'm closing as a low priority :).

**Comment by francoischalifour** [comment]
I'm wondering if adding OpenSearch directly to DocSearch isn't a bit too opinionated since DocSearch is meant to be plugged to multiple websites. However, supporting routing would allow this.

The challenge is that we need to detect that the URL loaded contains the search query parameter (e.g. `https://material-ui.com/getting-started/installation/?query=api`). We'd then need to focus the pre-filled input and to open the dropdown.

Thanks for creating the ticket, that's a feature worth investigating!
