### ISSUE TITLE
The anchor in returned hits is not consistent with GitHub anchor

### ISSUE THREAD

**Issue by YiniXu9506** [algolia/docsearch#852]
**Do you want to request a _feature_ or report a _bug_?**
Request a _feature_

**What is the current behavior?**
The rule of anchor processing is different from the anchor processing rule in GitHub.

An h4 in my markdown file is :
```
#### 4.1.8 用 Sqoop 批量写入 TiDB 数据，虽然配置了 `--batch` 选项，但还是会遇到 `java.sql.BatchUpdateExecption:statement count 5001 exceeds the transaction limitation` 的错误，该如何解决？
```

In GitHub, the h4 anchor is 
```
418-用-sqoop-批量写入-tidb-数据虽然配置了---batch-选项但还是会遇到-javasqlbatchupdateexecptionstatement-count-5001-exceeds-the-transaction-limitation-的错误该如何解决
```

However, Algolia returns the anchor:
```
"4-1-8-用-sqoop-批量写入-tidb-数据-虽然配置了-batch-选项-但还是会遇到-java-sql-batchupdateexecption-statement-count-5001-exceeds-the-transaction-limitation-的错误-该如何解决"
```

**What is the expected behavior?**
Users usually cannot scroll to the target position when using algolia's returned anchor. We expect the returned anchor follow the GitHub process rule. Or is there any other way to solve this problem? Thanks!

[1]: https://github.com/algolia/docsearch-configs
[2]: https://community.algolia.com/docsearch/config-file.html
[3]: (https://jsfiddle.net/)

**Comment by s-pace** [comment]
👋 @YiniXu9506 

Could you provide the URL of your website so that we can have a look please?

Redirection from DocSearch results usually works. Redirection scrolls down to the right anchor thanks to the `id` or `name` attribute available from your website. [See here for more details](https://community.algolia.com/docsearch/tips.html#add-anchors-to-headings).

**Comment by YiniXu9506** [comment]
The URL of my website is https:pingcap.com

**Comment by s-pace** [comment]
Please note that our crawler only focus on HTML. The translation from markdown to HTML made by GitHub pages is not in our hands

I have investigated into your issue and it seems that the crawler does correctly extract the anchor since it loads the page without JS rendering. Without this rendering (using `curl` for example), the anchor is `4-1-8-用-sqoop-批量写入-tidb-数据-虽然配置了-batch-选项-但还是会遇到-java-sql-batchupdateexecption-statement-count-5001-exceeds-the-transaction-limitation-的错误-该如何解决` as you can see on the following screenshot:
![image](https://user-images.githubusercontent.com/32097720/65675384-66e70d80-e04e-11e9-9f2e-7a00927fec3f.png)

My take is that your website uses JS to post process the anchor.

You could use [the configuration `js_render`](https://community.algolia.com/docsearch/config-file.html#js_render-optional) to mitigate such error. However the crawl will be too long for your website. We avoid using a browser emulation only for an anchor issue. Please avoid the need to do enable client side rendering and make sure `id` attribute are the same with and without JS rendering. It does work this way on other part of your website.

Once this is done, the next crawl will pick up the right anchor and the navigation will be solved.

Closing this issue as it is not related to the DocSearch's crawler. Feel free to ping if you encounter any roadblock along the way.
