### ISSUE TITLE
How to get content from a paragraph

### ISSUE THREAD

**Issue by YiniXu9506** [algolia/docsearch#874]
I want to report a feature in this issue.

My project index = pingcap, the config file can be found [here](https://github.com/algolia/docsearch-configs/blob/master/configs/pingcap.json). 

I built the search UI, expecting to display the title, url and a highlight content of each hit. But some of hits without content, I assign the value of a level with `matchLevel: "full"` in `_highlightResult.hierarchy` to `newContent` in the hit without content.

![image](https://user-images.githubusercontent.com/34967660/67279593-e48f2380-f4fd-11e9-9004-698c8f837398.png)

But I find there is a paragraph under this anchor, why Algolia returns null not the paragraph contains the matched word?

Please follow this steps to see my question. 
1. Browse to https://pingcap.netlify.com/search/docs/v3.0/?q=placement
3. You will see one hit `TiDB FAQ` . I assign a new content in the red box since I got the original hit without content.
![image](https://user-images.githubusercontent.com/34967660/67279395-78acbb00-f4fd-11e9-8fca-3c5096279d20.png)
4. You will jump to [this page](https://pingcap.com/docs/v3.0/faq/tidb/#what-is-the-respective-responsibility-of-tidb-tikv-and-pd-placement-driver) if you click this hit. There is a highlight word under the anchor `#what-is-the-respective-responsibility-of-tidb-tikv-and-pd-placement-driver`
![image](https://user-images.githubusercontent.com/34967660/67279719-23bd7480-f4fe-11e9-80bb-af1bdaecbdbb.png)

There are many hits like this. Do I need to change the config to get the first paragraph with matched word under the anchor? 

@s-pace PTAL, thanks!

**Comment by s-pace** [comment]
The issue you were struggling with is due to the way we build a DocSearch index. Every item created by the HUB does not always have a `content` attribute set. You can [find some more details regarding this strategy at this exact step](https://community.algolia.com/docsearch/how-do-we-build-an-index.html#we-iterate-through-the-payload-and-start-pushing-records).

I have updated and built your index (run a crawl) to avoid this behaviour. From now, every item created from your website by the scraper will have a `content` attribute set. This is done [thanks to this `only_content_level` config setting](https://community.algolia.com/docsearch/config-file.html#only_content_level-optional).
